apiVersion: v1
kind: Service
metadata:
  name: fastapi-mlops-backend-service
spec:
  selector:
    app: fastapi-mlops-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP